server:
  port: 8010
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.114.23:3306/music_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root          # 数据库账号和密码
    password: Hwh!149301
    type: com.alibaba.druid.pool.DruidDataSource
    jackson:
      date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tDN4ZVjwPEHPUEg8GDB
    accessKeySecret: 9f94SyDoiChgPrbAikKiPof4kmLDKW
    bucketName: music-android
